import calendar from "./assets/icon_calendar.png";
import phone from "./assets/icon_phone.png";
import theo from "./assets/photo/theo.png";
import alexandre from "./assets/photo/alexandre.png";
import anthony from "./assets/photo/anthony.png";
import cedric from "./assets/photo/cedric.png";
import luc from "./assets/photo/luc.png";
import maxime from "./assets/photo/maxime.png";
import nico from "./assets/photo/nico.png";
import olga from "./assets/photo/olga.png";
import paul from "./assets/photo/paul.png";
import yann from "./assets/photo/yann.png";
import anita from "./assets/photo/anita.png";
import robin from "./assets/photo/robin.png";
import julien from "./assets/photo/julien.png";
import sophie from "./assets/photo/sophie.png";
import paulC from "./assets/photo/paulC.png";
import ophelie from "./assets/photo/ophelie.png";

const DataGeolocalisation = [
  {
    id: 1,
    lastname: "Dr Labadie",
    firstname: "Anthony",
    pathologie: "Kinésithérapeute",
    note: "3.9",
    reviews: "(54 reviews)",
    image: anthony,
    adress: "136 rue Henri Laffite Bordeaux",
    icon1: calendar,
    icon2: phone,
  },
  {
    id: 2,
    lastname: "Dr Anache",
    firstname: "Théophile,",
    pathologie: "Kinésithérapeute",
    note: "4.9",
    reviews: "(260 reviews)",
    image: theo,
    adress: "18 rue Victor Hugo Bordeaux",
    icon1: calendar,
    icon2: phone,
  },
  {
    id: 3,
    lastname: "Dr Pré",
    firstname: "Alexandre",
    pathologie: "Kinésithérapeute",
    note: "4.9",
    reviews: "(141 reviews)",
    image: alexandre,
    adress: "25 rue henri Brunet Bordeaux",
    icon1: calendar,
    icon2: phone,
  },
  {
    id: 4,
    lastname: "Dr Mounier",
    firstname: "Cédric",
    pathologie: "Kinésithérapeute",
    note: "3.7",
    reviews: "(129 reviews)",
    image: cedric,
    adress: "18 rue Jean Hameau Bordeaux",
    icon1: calendar,
    icon2: phone,
  },
  {
    id: 1,
    lastname: "Dr Anita",
    firstname: "Tabernacle",
    pathologie: "Infirmier(e)",
    note: "4.9",
    reviews: "(460 reviews)",
    image: anita,
    adress: "54 Bd Godart Bordeaux",
    icon1: calendar,
    icon2: phone,
  },
  {
    id: 2,
    lastname: "Dr Maximuss",
    firstname: "Proximuss",
    pathologie: "Infirmier(e)",
    note: "4.6",
    reviews: "(140 reviews)",
    image: maxime,
    adress: "12 rue Ausone Bordeaux",
    icon1: calendar,
    icon2: phone,
  },
  {
    id: 3,
    lastname: "Dr Jaubert",
    firstname: "Luc",
    pathologie: "Infirmier(e)",
    note: "3.5",
    reviews: "(34 reviews)",
    image: luc,
    adress: "318 rue Raymond ManaudBordeaux",
    icon1: calendar,
    icon2: phone,
  },
  {
    id: 4,
    lastname: "Dr Yasnopolskaïa",
    firstname: "Olga",
    pathologie: "Infirmier(e)",
    note: "4.7",
    reviews: "(624 reviews)",
    image: olga,
    adress: "11 Bd Aliénor d'aquitaine Bordeaux",
    icon1: calendar,
    icon2: phone,
  },
  {
    id: 1,
    lastname: "Dr Delisée",
    firstname: "Nicolas",
    pathologie: "Psychologue",
    note: "4.0",
    reviews: "(899 reviews)",
    image: nico,
    adress: "97 rue Pascal Triat Bordeaux",
    icon1: calendar,
    icon2: phone,
  },
  {
    id: 2,
    lastname: "Dr Battaut",
    firstname: "Paul",
    pathologie: "Psychologue",
    note: "4.2",
    reviews: "(444 reviews)",
    image: paul,
    adress: "171 rue Lucien Faure Bordeaux",
    icon1: calendar,
    icon2: phone,
  },
  {
    id: 3,
    lastname: "Dr Bausse",
    firstname: "Ophélie",
    pathologie: "Psychologue",
    note: "4.9",
    reviews: "(998 reviews)",
    image: ophelie,
    adress: "46 rue de Verdun Bordeaux",
    icon1: calendar,
    icon2: phone,
  },
  {
    id: 4,
    lastname: "Dr Dussilol",
    firstname: "Sophie",
    pathologie: "Psychologue",
    note: "4.6",
    reviews: "(521 reviews)",
    image: sophie,
    adress: "68 rue Stéhelin Bordeaux",
    icon1: calendar,
    icon2: phone,
  },
  {
    id: 1,
    lastname: "Dr Michel",
    firstname: "Robin",
    pathologie: "Aide à domicile",
    note: "4.7",
    reviews: "(224 reviews)",
    image: robin,
    adress: "147 rue Cérey Bordeaux",
    icon1: calendar,
    icon2: phone,
  },
  {
    id: 2,
    lastname: "Dr Stefanutti",
    firstname: "Yann",
    pathologie: "Aide à domicile",
    note: "4.1",
    reviews: "(333 reviews)",
    image: yann,
    adress: "2 rue de Capeyron Bordeaux",
    icon1: calendar,
    icon2: phone,
  },
  {
    id: 3,
    lastname: "Duss",
    firstname: "Julien",
    pathologie: "Aide à domicile",
    note: "4.3",
    reviews: "(463 reviews)",
    image: julien,
    adress: "93 rue Naujac Bordeaux",
    icon1: calendar,
    icon2: phone,
  },
  {
    id: 4,
    lastname: "Castaing",
    firstname: "Paul",
    pathologie: "Aide à domicile",
    note: "4.6",
    reviews: "(521 reviews)",
    image: paulC,
    adress: "78 rue Larochez Bordeaux",
    icon1: calendar,
    icon2: phone,
  },
];

export default DataGeolocalisation;
